// Copyright 2006-2021 ClickTale Ltd., US Patent Pending

window.ClickTaleGlobal = window.ClickTaleGlobal || {};
window.ClickTaleSettings = window.ClickTaleSettings || {};

ClickTaleGlobal.init = ClickTaleGlobal.init || {};
ClickTaleGlobal.scripts = ClickTaleGlobal.scripts || {};

ClickTaleGlobal.scripts.filter = ClickTaleGlobal.scripts.filter || (function () {
	var recordingThreshold = Math.random() * 100;

	return {
		isRecordingApproved: function(percentage) {
			return recordingThreshold <= percentage;
		}
	}
})();
	
		
// Copyright 2006-2021 ClickTale Ltd., US Patent Pending
// PID: 328



/*browsers exclusion start*/ ClickTaleSettings.PTC.doOnlyWhen = function (toDoHandler, toCheckHandler, interval, times, failHandler) {
            if ((!toDoHandler) || (!toCheckHandler)) return;
            if (typeof interval == 'undefined') interval = 1000;
            if (typeof times == 'undefined') times = 20;
        
            if (--times < 0) {
                if (typeof failHandler === 'function') {
                    failHandler();
                }
                return;
            }
            if (toCheckHandler()) {
                toDoHandler();
                return;
            }
        
            setTimeout(function () { ClickTaleSettings.PTC.doOnlyWhen(toDoHandler, toCheckHandler, interval, times, failHandler); }, interval);
        }
        ClickTaleSettings.PTC.doOnlyWhen(function () { 
            if (window.ClickTaleSettings.PTC.okToRunPCC) { 
                (function(){
                    window.ClickTaleSettings = window.ClickTaleSettings || {};
                    ClickTaleSettings.PTC = ClickTaleSettings.PTC || {};
                    ClickTaleSettings.PTC.originalPCCLocation = 'P16_PID328';
                    
                    var aa="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var f in d)Object.prototype.hasOwnProperty.call(d,f)&&(a[f]=d[f])}return a},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ca="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function da(a,b){if(b){var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}da("Object.assign",function(a){return a||aa});var ea;function h(a,b,c,d,f){a&&b&&("undefined"==typeof c&&(c=1E3),"undefined"==typeof d&&(d=20),0>--d?"function"===typeof f&&f():b()?a():setTimeout(function(){h(a,b,c,d,f)},c))}
function fa(a){var b="someText".trim,c=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;ea=b&&!b.call(new String("\ufeff\u00a0"))?function(d){return null==d?"":b.call(d)}:function(d){return null==d?"":(d+"").replace(c,"")};return ea(a)}function l(a){if(!a)return!1;var b=a.getRootNode?a.getRootNode({composed:!1}):a.ownerDocument;return!!(a.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_CONTAINS&&(a.offsetWidth||a.offsetHeight||a.getClientRects().length))}
function ha(a){return"string"==typeof a?ha(document.querySelectorAll(a)):Array.prototype.filter.call(a,function(b){return l(b)})};function m(a,b){b||(b=document);return b instanceof Element||b instanceof Document?Array.prototype.slice.call(b.querySelectorAll(a)):"string"===typeof b?m(a,document.querySelectorAll(b)):Array.isArray(b)||b instanceof HTMLCollection||b instanceof NodeList?Array.prototype.reduce.call(b,function(c,d){return c.concat(Array.prototype.slice.call(d.querySelectorAll(a)))},[]):[]}
function n(a,b){if(a&&a.nodeType&&9===a.nodeType)return!1;var c=Element.prototype;n=function(d,f){return d&&document.documentElement.contains(d)?n.b.call(d,f):!1};n.b=c.webkitMatchesSelector||c.mozMatchesSelector||c.msMatchesSelector||c.matches;return n(a,b)}function q(a,b){q=Element.prototype.closest?function(c,d){return c&&c instanceof Element?Element.prototype.closest.call(c,d):null}:function(c,d){for(;c&&!n(c,d);)c=c.parentElement;return c};return q(a,b)};var r=!1,ia=Object.defineProperty&&Object.defineProperty({},"passive",{get:function(){r=!0}});document.addEventListener("test",function(){},ia);var t=r?{passive:!0,capture:!0}:!0,v=r?{passive:!0,capture:!1}:!1,ja=0;
function y(a){function b(){2==++c&&a()}if(!~y.b.indexOf(a)){y.b.push(a);var c=0;ka(b);if("function"==typeof ClickTaleIsRecording&&!0===ClickTaleIsRecording())b();else{var d=window.ClickTaleOnRecording||function(){};window.ClickTaleOnRecording=function(){b();return d.apply(this,arguments)}}}}y.b=[];function ka(a){function b(){c||(c=!0,a())}var c=!1;"loading"!=document.readyState?b():document.addEventListener&&document.addEventListener("DOMContentLoaded",b,!1)}
function z(a,b,c,d,f){if("string"===typeof b&&-1!=b.indexOf(" "))return b.split(/\s+/).forEach(function(g){return z(a,g,c,d,f)}),a;if("string"===typeof a)Array.prototype.forEach.call(document.querySelectorAll(a),function(g){z(g,b,c,d,f)});else if(a instanceof Array||a instanceof NodeList)Array.prototype.forEach.call(a,function(g){z(g,b,c,d,f)});else{var e="";"string"==typeof c&&("mouseenter"==b?(b="mouseover",e="mouseenter"):"mouseleave"==b&&(b="mouseout",e="mouseleave"));a.addEventListener(b,function(g,
p,k,w,x,u){return function(A){if("function"===typeof k)k.apply(this,arguments),x&&g.removeEventListener(p,arguments.callee,t);else{var F=A.relatedTarget,G=q(A.target,k);G&&g.compareDocumentPosition(G)&Node.DOCUMENT_POSITION_CONTAINED_BY&&("mouseenter"==u||"mouseleave"==u?F&&(F==G||G.compareDocumentPosition(F)&Node.DOCUMENT_POSITION_CONTAINED_BY)||w.apply(G,arguments):w.apply(G,arguments),x&&g.removeEventListener(p,arguments.callee,t))}}}(a,b,c,d,f,e),t)}return a}
function la(a,b){document.addEventListener("mouseup",function(c){a===c.target&&b();document.removeEventListener("mouseup",arguments.callee,t)},t)}function ma(a,b){function c(d){document.removeEventListener("touchend",arguments.callee,t);a===d.target&&b()}document.addEventListener("touchend",c,t);document.addEventListener("touchmove",function(d){document.removeEventListener("touchmove",arguments.callee,t);document.removeEventListener("touchend",c,t)},t)}
function B(a,b){var c=C();c&&(B=c.m?ma:la,B(a,b))}function D(a,b){if("string"===typeof a)Array.prototype.forEach.call(document.querySelectorAll(a),function(d){D(d,b)});else if(a instanceof Array||a instanceof NodeList)Array.prototype.forEach.call(a,function(d){D(d,b)});else{var c=document.createEvent("HTMLEvents");c.initEvent(b,!0,!0);return!a.dispatchEvent(c)}};function E(a){if(window.CSS&&"function"===typeof window.CSS.escape)E=function(d){return window.CSS.escape.call(window.CSS,d)};else{var b=/([\0-\x1f\x7f]|^-?\d)|^-$|[^\x80-\uFFFF\w-]/g,c=function(d,f){return f?"\x00"===d?"\ufffd":d.slice(0,-1)+"\\"+d.charCodeAt(d.length-1).toString(16)+" ":"\\"+d};E=function(d){return d.replace(b,c)}}return E(a)}function na(a){return btoa(encodeURIComponent(a).replace(/%([0-9A-F]{2})/g,function(b,c){return String.fromCharCode(+("0x"+c))}))};function oa(a){window._uxa=window._uxa||[];window._uxa.push.apply(window._uxa,arguments)}function pa(a){a=void 0===a?window.location.pathname+window.location.hash.replace("#","?__"):a;oa(["trackPageview",a])}function H(a,b){oa(["trackDynamicVariable",{key:a,value:b}])};function I(a){window.ClickTaleMonitor&&"function"===typeof window.ClickTaleMonitor.addEvent&&(I=function(b){isNaN(b)||ClickTaleMonitor.addEvent(b)},I(a))}function qa(){if(window.ClickTaleMonitor&&ClickTaleMonitor.Settings&&"function"===typeof ClickTaleMonitor.Settings.get){var a=ClickTaleMonitor.Settings.get();a.monitor&&a.monitor.onStop&&"function"==typeof a.monitor.onStop&&(a.monitor.onStop(function(){a.started=!1}),ClickTaleMonitor.App.prototype.dispose.call(a.monitor,!1,!1,!0))}}
function ra(a,b){window.ClickTaleMonitor&&"function"===typeof ClickTaleMonitor.addPageTag&&(ra=function(c,d){!isNaN(c)&&d&&ClickTaleMonitor.addPageTag(c,d)},ra(a,b))}function J(a,b){window.ClickTaleMonitor&&"function"===typeof ClickTaleMonitor.addDynamicAction&&(J=function(c,d){!isNaN(c)&&d&&ClickTaleMonitor.addDynamicAction(c,d)},J(a,b))}
function sa(a,b){if(window.ClickTaleMonitor&&"function"==typeof ClickTaleMonitor.restart&&K()){var c=c||500;if(ta){ta=!1;var d=ClickTaleMonitor.Settings.get(),f=d.shouldStartMonitorCallback||function(){},e="";d&&d.config&&d.config.transport&&(e=d.config.transport.url||"");qa();d=ClickTaleMonitor.Settings.get();e&&d.configure({transport:{url:e}});"function"===typeof d.shouldStartMonitor&&d.shouldStartMonitor(f);ClickTaleMonitor.restart(a,b);setTimeout(function(){ta=!0},c)}}}var ta=!0;
function K(){var a=!1;if(window.ClickTaleMonitor&&"function"===typeof window.ClickTaleMonitor.isMonitoring&&window.ClickTaleMonitor.isMonitoring())a=!0;else if(window.ClickTaleMonitor){var b=window.ClickTaleMonitor&&ClickTaleMonitor.Settings&&"function"==typeof ClickTaleMonitor.Settings.get?ClickTaleMonitor.Settings.get():null;if(b)b.onStart(function(){K.b=!0})}else return h(K,function(){return!!window.ClickTaleMonitor},1E3,10),!1;K=function(){return K.b};K.b=a;return K.b}K.b=!1;K();function L(a){"function"===typeof ClickTaleExec&&ClickTaleExec(a)}function ua(){"function"===typeof ClickTaleStop&&ClickTaleStop()}function M(a,b){"function"===typeof ClickTaleEvent&&(b?!0!==M.b[a]&&(M.b[a]=!0,ClickTaleEvent(a)):ClickTaleEvent(a))}M.b={};function va(a){"function"===typeof ClickTaleRegisterFormSubmit&&ClickTaleRegisterFormSubmit(a)}function wa(a){"function"===typeof ClickTaleRegisterFormSubmitFailure&&(a?ClickTaleRegisterFormSubmitFailure(a):ClickTaleRegisterFormSubmitFailure())}
function xa(a){"function"===typeof window.ClickTaleRegisterElementAction&&ClickTaleRegisterElementAction("click",a)}
function ya(a,b){a&&"object"==typeof a&&"string"==typeof b&&(window.ClickTaleContext&&-1!=document.referrer.indexOf(location.hostname)&&window.parent.ct&&window.parent.ct.ElementAddressing&&"function"===typeof window.parent.ct.ElementAddressing.forceSetCustomElementID?window.parent.ct.ElementAddressing.forceSetCustomElementID(a,b):(window.ClickTaleContext||"function"!==typeof ClickTaleSetCustomElementID||-1==ClickTaleSetCustomElementID.toString().indexOf("duplicate registration of custom id")?window.ClickTaleSetCustomElementID=
window.ClickTaleSetCustomElementID||function(c,d){c.ClickTale=c.ClickTale||{};c.ClickTale.CustomID=d}:ya=function(c,d){c.ClickTale=c.ClickTale||{};c.ClickTale.CustomID=d},window.ClickTaleSetCustomElementID(a,b)))}
function za(){Array.prototype.forEach.call(document.querySelectorAll('[id]:not([id=""])'),function(a){if(!n(a,'input[type="hidden"], script')){var b=a.getAttribute("id");b.match(/(?:\r|\n)/)&&Aa("ctlib.api.SetCustomElementIdDuplicates: ids with line break found!");a=document.querySelectorAll('[id="'+E(b)+'"]');var c=Ba;1<a.length&&!c[b]&&(c[b]=!0,Array.prototype.forEach.call(a,function(d,f){ya(d,b.replace(/(\r|\n|\r\n|\s+)+/g,"_").replace(/\W/g,"_")+"_"+f)}))}})}var Ba={};
function Ca(a,b){"function"===typeof ClickTaleLogical&&(M.b={},Ba={},N.b&&N.b instanceof Da&&N.b.clear(),b?ClickTaleLogical(a,b):ClickTaleLogical(a))}function C(){if("function"===typeof ClickTaleDetectAgent){var a=ClickTaleDetectAgent();if(a)return C=function(){return a},C()}return null}function Aa(a){"function"===typeof ClickTaleNote&&ClickTaleNote(a)}
function O(a){if("function"===typeof ClickTaleRegisterTouchAction){var b=a.getBoundingClientRect();ClickTaleRegisterTouchAction(a,b.left+document.body.scrollLeft,b.top+document.body.scrollTop)}}
function Ea(a,b,c){if("boolean"!=typeof P){var d=C();d&&(P=!!d.m)}a||(a="mousedown",P&&(a="touchstart"));c=c||"img, a, button, textarea, input, select";P&&(c+=", label[for]");z(document,a,c,function(f){var e=f.target,g=this;if(!b||!n(this,b))if(P)if(n(this,"label[for]"))B(e,function(w){return function(){var x,u;(x=w.getAttribute("for"))&&(u=document.getElementById(x))&&O(u)}.bind(g)}(e,f));else{var p=-1,k=function(w){clearTimeout(p);document.removeEventListener("touchstart",arguments.callee,v);B(e,
function(x){return function(){function u(F){document.removeEventListener("touchend",arguments.callee,v);clearTimeout(A)}var A=-1;document.addEventListener("touchend",u,v);A=setTimeout(function(){document.removeEventListener("touchend",u,v);O(x)},50)}.bind(g)}(e,f))};document.addEventListener("touchstart",k,v);p=setTimeout(function(){document.removeEventListener("touchstart",k,v);O(e)},50)}else B(e,function(w,x){return function(){function u(F){F.target===w&&(Fa=!0);document.removeEventListener("click",
arguments.callee,!0);clearTimeout(A)}var A=setTimeout(function(){Fa||xa(x);document.removeEventListener("click",u,!0);Fa=void 0},200);document.addEventListener("click",u,!0)}.bind(g)}(e,f))})}var P,Fa;
function Ga(a){var b=Ha,c=Ia,d=Ja;if(Ka){Ka=!1;var f=f||400;d?(ua(),window.ClickTaleIncludedOnDOMReady=!0,window.ClickTaleIncludedOnWindowLoad=!0,"function"===typeof ClickTaleUploadPage&&ClickTaleUploadPage(void 0,void 0),Ca(a.href,c)):(Array.isArray(window.ClickTaleOnStop)&&window.ClickTaleOnStop.forEach(function(e){if("function"===typeof e)try{e.call(window)}catch(g){}}),pa(a.pathname));sa(a,c);b();clearTimeout(La);La=setTimeout(function(){Ka=!0},f)}}var La=-1,Ka=!0;
function Ma(a){"function"===typeof ClickTaleAddAugmentElementPathHandler&&ClickTaleAddAugmentElementPathHandler("Linkanalytics",a)}
function Na(){var a=[['[data-test-id=ch_payment_paypal],[data-test-id="ch_payment_verifone"]',!0]];Oa=a;var b="";a.forEach(function(c){!0===c[1]&&(b+=","+c[0])});b&&Ea("","",b.replace(/^,/,""));Ma(function(c){return function(d){for(var f=0,e=c.length;f<e;f++){var g=c[f],p=g[0];if(d&&n(d,p)&&(p=g[2],"function"!=typeof p||p()))return{data:{interesting:g[1]}}}return null}}(Oa))}var Oa=[];
function Da(){this.g=!1;this.b="";this.init=function(a){this.g||(this.g=!0,document.addEventListener("input",this.h,t));this.j(a);this.b=this.b?this.b+","+a:a};this.h=function(a){a=a.target;if(n(a,this.b)){var b=m(this.b).indexOf(a);L("document.querySelectorAll('"+this.b+"')["+b+"].value = Base64Decode('"+na(a.value)+"');")}}.bind(this);this.j=function(a){var b="";m(a).forEach(function(c,d){b+="document.querySelectorAll('"+a+"')["+d+"].value = Base64Decode('"+na(c.value)+"'); "});b&&L(b)};this.clear=
function(){document.removeEventListener("input",this.h,t);this.g=!1;this.b=""}}function N(){N.b=N.b||new Da;N.b.init('input[data-test-id="searchBar"]')}N.b=null;var Q=M,R=D,Pa=ya;function S(a,b){return a instanceof Element?b instanceof Element?a===b:n(a,b):!1}var T=q,U=ha,Qa=B;var Ja=!1,V=document.location.pathname.toLowerCase(),W=!1,Ra=!0,Ia=location.href,X,Sa,Y=!0,Ta=0,Ua={"Please provide a valid credit card number":"DIY O | Payment | Invalid Card Nr","Please enter your end month":"DIY O | Payment | Error Date","Please enter your end year":"DIY O | Payment | Error Date","Please enter your name as it appears on your card":"DIY O | Payment | Invalid name","Please provide a 19 digit number":"DIY O | Checkout | Gift Cart error","Please provide a UK postcode":"DIY O | Checkout | Invalid Postcode",
"Please enter a valid email address.":"DIY O | Login | Email Validation error","Please provide a valid contact number":"DIY O | Checkout | Phone Number Error"},Va={"View product":"DIY | PLP | View product","Show more":"DIY | PLP | Filter \u2013 Show More","Add to basket":"Add to cart"},Wa={"[data-test-id='ch_payment_paypal'],[data-test-id=ch_payment_verifone]":"Payment Details","#content,[data-test-id=ch_payment_verifone]":"Payment Details","[data-name=addPaymentCard], #ch_payment":"Credit Card Form",
"[data-name='finalise'],[data-test-id=finaliseOptilePaymentSubmission]":"Paypal Form",".ch-contact-details,[data-test-id=lookupAddressButton]":"Enter contact details"};
function Xa(){var a;h(function(){var b=a.sheet.insertRule;a.sheet.insertRule=function(c,d,f){var e=arguments[0];e&&"string"==typeof e&&setTimeout(function(){L("window['fixSheetIssue']('"+escape(e)+"');")},10);return b.apply(this,arguments)}},function(){a=document.querySelector("style[data-styled]");return!!a},250,25,function(){"function"===typeof ClickTaleField&&ClickTaleField("style[data-styled]","never found and time passed")})}
function Ya(a){var b=Object.assign({},document.location);b.search="?"+a;b.href=b.href.split("?")[0]+b.search;Ga(b)}function Za(a){setTimeout(function(){h(function(){Array.prototype.forEach.call(document.querySelectorAll(a),function(b){if("hidden"!=b.type){var c={target:b};"function"===typeof ClickTaleRegisterElementAction&&ClickTaleRegisterElementAction("ElmPos",c);$a(b)}})},function(){return!!document.querySelector(a)},1E3,20)},300)}
function $a(a){a&&h(function(){var b=a.ClickTale.EPID;setTimeout(function(){if(window.ClickTaleGlobal&&window.ClickTaleGlobal.symbols&&"function"==typeof window.ClickTaleGlobal.symbols.WRa&&!isNaN(window.WRInitTime)){var c=a.nodeName.toLowerCase();if("input"===c)if(/(?:radio|checkbox)/.test(a.type))var d=a.checked?1:0;else"string"===typeof a.value&&(d=a.value.length);else"select"===c&&(d=a.selectedIndex);void 0!==d&&window.ClickTaleGlobal.symbols.WRa({a:"change",i:b,t:Date.now()-window.WRInitTime,
v:d})}},150)},function(){return a.ClickTale&&a.ClickTale.EPID},100,20)}function ab(){"boolean"===typeof W&&"function"===typeof ClickTaleField&&ClickTaleField("isMobile",W.toString())}function bb(){for(var a in Wa)if(1<document.querySelectorAll(a).length)return Wa[a]}
function cb(a,b,c){var d;h(function(){var f=U(document.querySelectorAll(a));if(f.length){"function"===typeof ClickTaleFormDisableAll&&ClickTaleFormDisableAll();var e=[b];Sa="function"===typeof window.ClickTaleLogicalForm?window.ClickTaleLogicalForm(c,f,e):0;Za(a);Q(c+" FA")}},function(){return(d=document.querySelector(b))&&window.ClickTaleLogicalForm&&window.ClickTaleFormDisableAll&&U(document.querySelectorAll(a)).length},250,30)}
function db(){var a=Sa;a&&(va(a),R(document.body,"keydown"),setTimeout(function(){h(function(){wa(a);R(document.body,"keydown")},function(){return 0<U(".ch-contact-details ._0554c3ab").length},500,10)},1E3))}function eb(a,b){if(W)O(b);else{var c={},d;for(d in a)c[d]=a[d];c.target=b;c.srcElement=b;xa(c);a?Aa("function: RegisterElementActionAutoNewEvent , event: "+a.type):Aa("function: RegisterElementActionAutoNewEvent")}}
function fb(){var a=document.querySelector(".slick-slider");a&&(a=a.querySelectorAll(".slick-slide:not(.slick-cloned)").length,0<a&&H("PDP images",a));var b,c,d=!1,f=!1;h(function(){(c=document.querySelector('[data-test-id="PrimaryImage"] img'))&&-1<c.src.indexOf("i?")&&(H("imagery-lead-lifestyle","true"),d=!0,H("imagery-Include-Lifestyle","true"));b=document.querySelectorAll("section .slick-slider > button + .slick-list img");b=Array.prototype.slice.call(b);b.forEach(function(e){!d&&-1<e.src.indexOf("i?")&&
(d=!0,H("imagery-Include-Lifestyle","true"));!f&&-1<e.src.indexOf("t_bq?")&&(f=!0,H("imagery-Include-Technical-Drawings-Illustrations","true"))});document.querySelector('[data-test-id="Video"]')&&H("imagery-Product-Video","true")},function(){return!!document.querySelectorAll("section .slick-slider > button + .slick-list")},250,10)}
function gb(){h(function(){H("Reviews available","true");var a={".bv-secondary-rating-summary-stars .bv-secondary-rating-summary-rating":"Star Rating",'[data-test-id="hero-rating"] [data-test-id="RatingTotalReviews"]':"Reviews Number",'div[aria-labelledby="bv-inline-histogram-ratings-star-label-5"] div.bv-inline-histogram-ratings-score>span':"Five Star Reviews",'div[aria-labelledby="bv-inline-histogram-ratings-star-label-1"] div.bv-inline-histogram-ratings-score>span':"One Star Reviews"};for(c in a){var b=
document.querySelector(c);if(b=b?b.textContent:"")b=Math.round(b.replace(/[()]/g,"")),!isNaN(b)&&H(a[c],b)}var c=document.querySelector('div[aria-labelledby="bv-inline-histogram-ratings-star-label-2"] div.bv-inline-histogram-ratings-score>span');b=document.querySelector('div[aria-labelledby="bv-inline-histogram-ratings-star-label-3"] div.bv-inline-histogram-ratings-score>span');a=document.querySelector('div[aria-labelledby="bv-inline-histogram-ratings-star-label-4"] div.bv-inline-histogram-ratings-score>span');
c&&b&&a&&(c=parseInt(c.textContent,10),b=parseInt(b.textContent,10),a=parseInt(a.textContent,10),isNaN(c)||isNaN(b)||isNaN(a)||H("4,3,2 Star Reviews",c+b+a));Array.prototype.forEach.call(document.querySelectorAll("div.bv-secondary-rating-summary-bars-container"),function(d){var f=d.querySelector("div.bv-secondary-rating-summary-id");f=f?fa(f.textContent):"";d=(d=d.querySelector("span.bv-secondary-rating-summary-rating"))?Math.round(d.textContent):"";f&&!isNaN(d)&&H(f,d)})},function(){return!!document.querySelector(".bv-secondary-rating-summary-stars .bv-secondary-rating-summary-rating")},
500,6,function(){H("Reviews available","false")})}
function Ha(){za();Ia=location.href;V=document.location.pathname.toLowerCase();Xa();if(Ra)Ra=!1;else for(var a=window.ClickTaleSettings&&window.ClickTaleSettings.PTC&&window.ClickTaleSettings.PTC.InitFuncs?window.ClickTaleSettings.PTC.InitFuncs:[],b=0,c=a.length;b<c;b++)if("function"===typeof a[b])a[b]();Ja?ab():y(function(){Ja=!0;ab()});hb();-1<V.indexOf(".prd")&&(fb(),gb());-1<V.indexOf("checkout")&&(Ta=0,h(function(){Q("DIY O | Checkout | "+X);ra(37989,"DIY O | Checkout | "+X);setTimeout(function(){"Credit Card Form"==
X&&cb("input,select,#ch_payment [data-test-id=address_card]",'[data-test-id="addPaymentCardButton"]',"Add Payment Card")},1500)},function(){X=bb();return!!X},250,25));h(function(){H("PostCode Box","true")},function(){return l(document.querySelector('[data-test-id="check-post-code-btn"]'))},250,40);ib();cb("input,select",'.ch-contact-details [data-test-id="lookupAddressButton"]',"Enter Contact Details")}
function jb(){-1<V.indexOf("checkout")&&setTimeout(function(){if(document.querySelector('[data-name="v2ABCheckoutSignInFormName"] [data-test-id="email-field-error"]')){var a=document.querySelector('[data-name="v2ABCheckoutSignInFormName"] [data-test-id="email-field-error"]').innerText;a&&-1<a.indexOf("enter a valid email addres")?(Q("Login | Please enter valid email address"),I(55454)):a&&-1<a.indexOf("Email address already registered")&&(Q("Login | Email already registered"),I(55453))}a=document.querySelectorAll('[data-test-id="undefined-error"]');
a.length&&(1<document.querySelectorAll("[data-name=addPaymentCard], #ch_payment").length&&(Q("DIY O | Payment | Inline Error",!0),J(37979,"DIY O | Payment | Inline Error")),Array.prototype.forEach.call(a,function(b){b&&Ua[b.innerText]&&(Q(Ua[b.innerText],!0),J(37979,Ua[b.innerText]))}))},500)}
function kb(){var a=Sa;a&&(va(a),R(document.body,"keydown"),setTimeout(function(){h(function(){wa(a);R(document.body,"keydown")},function(){return 0<U('[data-test-id="undefined-error"]').length||l(document.querySelector('[data-test-id="alert-title"]'))},500,75)},1E3))}
function hb(){var a;h(function(){-1<a.innerText.indexOf("Click & Collect")?(Q("DIY O | Click & Collect Unavailable Error Message"),I(33527)):-1<a.innerText.indexOf("unable to complete your order")?(Q("DIY O | Unable to Complete Order Error Message"),I(33528)):-1<a.innerText.indexOf("We have moved")&&(Q("DIY O | Product Unavailable Error Message"),I(33529))},function(){a=document.querySelector("#content [role=alert]");return!!a},500,10)}
function lb(){setTimeout(function(){Ga(document.location)},3E3)}
function ib(){var a=document.location.pathname,b;h(function(){var c=new MutationObserver(function(){var d=bb();X&&d&&d!=X&&-1<document.location.pathname.indexOf("checkout")&&(ClickTaleNote("Mutation1 Logical Page"),lb(),c.disconnect());a!=document.location.pathname&&(ClickTaleNote("Mutation2 Logical Page"),lb(),c.disconnect())});c.observe(b,{attributes:!1,childList:!0,subtree:!0})},function(){b=document.querySelector("#content");return!!b},200,20)}
function Z(a,b,c){setTimeout(function(){document.querySelector(a)&&-1<document.querySelector(a).innerText.indexOf(b)&&(Q(c,!0),J(37979,c))},500)}
function mb(){for(var a=document.querySelectorAll("._30ff2f6b "),b={f:0};b.f<a.length;b={f:b.f},b.f++)a[b.f].addEventListener("mouseenter",function(c){return function(){L('document.querySelectorAll("._30ff2f6b")['+c.f+'].querySelector("ul").setAttribute("style", "visibility: visible; opacity: 1; -webkit-transition-delay: .2s; transition-delay: .2s; z-index: 110;")')}}(b)),a[b.f].addEventListener("mouseleave",function(c){return function(){L('document.querySelectorAll("._30ff2f6b")['+c.f+'].querySelector("ul").setAttribute("style", "")')}}(b))}
function nb(){pa(document.location.pathname+"?cs_out_of_stock_at_selected_store")}
function ob(){if(!window.ClickTaleFirstPCCGo){window.ClickTaleFirstPCCGo=!0;var a=C();a&&(W=a.m);Na();Ha();mb();window.addEventListener("hashchange",function(){Q("Hash Changed");ClickTaleNote(location.href)});document.addEventListener("input",function(){jb()},!0);N();z(document,"keypress",'form[data-name="addPaymentCard"] input,button[data-test-id="addPaymentCardButton"],[data-test-id="placeOrderButton"]',function(b){13!=b.which&&13!=b.keyCode||!Y||(Y=!1,kb(),setTimeout(function(){Y=!0},500))});z(document,
W?"touchstart":"mousedown",'button[data-test-id="conflict-fulfilment-choice"],[data-name="v2ABCheckoutSignInFormName"] [data-test-id="buttonContinueSecurely"],[data-test-id="placeOrderButton"],button[data-test-id="addAddressButton"],button[data-test-id="payByCardButton"],button[data-test-id="addPaymentCardButton"],button[data-test-id=fulfilment-continue-button],._218999bf.ec08ce26,[data-test-id="addShippingAddress"],[data-test-id="confirmPaymentMethodCta"],[data-test-id=ch_payment_paypal],[data-test-id="ch_payment_verifone"],[data-test-id="checkoutAsGuestButton"],button,[data-test-id=product-panel],.promo-blocks article,.slick-slider [data-test-id=product-panel] a[data-test-id=product-panel-main-section],.slick-slider [data-test-id="arrow-handle-next"],.slick-slider [data-test-id="arrow-handle-previous"],.slick-slider li[class],.html-content img,.js-menu-children .menu-item,[data-test-id="app-header-burger-open"], a[data-test-id="secure-app-home-link"]',
function(b){var c=b.target;S(this,'button[data-test-id="addPaymentCardButton"],[data-test-id="placeOrderButton"]')&&Y&&(Y=!1,kb(),setTimeout(function(){Y=!0},500));Qa(c,function(d,f,e){return function(){S(e,'[data-name="v2ABCheckoutSignInFormName"] [data-test-id="buttonContinueSecurely"]')&&(Ta++,3<=Ta&&(Q("Action | Clicks continue securely 3+ times",!0),I(55456)),setTimeout(function(){if(l(document.querySelector('[role="alert"]'))){var k=document.querySelector('[role="alert"] [data-test-id="alert-title"]')&&
document.querySelector('[role="alert"] [data-test-id="alert-title"]').innerText;k&&-1<k.indexOf("more than one basket")&&(Q("Action | Login | More than 1 basket"),I(55455))}},800));T(e,'[data-test-id="app-header-burger-open"]')&&h(function(){Array.prototype.filter.call(document.querySelectorAll('a[data-test-id*="category-menu-link"]'),function(k,w){Pa(k,"ctMenuLinkID"+w)})},function(){var k=document.querySelector("#content");return k&&(k=k.querySelectorAll("div")[1])&&(k=k.children)?2==k.length:!1},
100,65);S(e,'[data-test-id="addShippingAddress"]')&&setTimeout(function(){document.querySelectorAll('[data-name="addShippingAddress"]')&&document.querySelectorAll('[data-name="addShippingAddress"]').length&&(Q("DIY O | Checkout | Select a Delivery Address"),I(32921))},500);S(e,"button[data-test-id=fulfilment-continue-button]")&&(hb(),h(function(){nb()},function(){return l(document.querySelector('[data-test-id="modal-overlay"] [data-test-id="alert-title"]'))},300,20));if(S(e,'button[data-test-id="conflict-fulfilment-choice"]'))h(function(){nb()},
function(){return l(document.querySelector('[data-test-id="modal-overlay"] [data-test-id="alert-title"]'))},300,20);else if(S(e,'[data-test-id=ch_payment_paypal],[data-test-id="ch_payment_verifone"]'))eb(f,e);else if(S(e,'[data-test-id="checkoutAsGuestButton"]'))Z('[data-name="checkoutGuestForm"]',"log you in right now","DIY O | Login | Error: Sorry we cant log you in "),Z('[data-name="checkoutGuestForm"]',"Please enter a valid email","DIY O | Login | Email Validation error"),Z('[role="alert"]',"Email address already registered",
"DIY O | Login | Error: already registered");else if(S(e,'[data-test-id="addAddressButton"]'))Z('[data-name="addContactAddress"]',"Number of digits in phone n","DIY O | Checkout | Phone Number Error"),db();else if(S(e,"[data-test-id=filters-facet-value]")){var g=T(e,".ab8a3b91");g&&g.querySelector("h4 span")&&(g=g.querySelector("h4 span").innerText,Q("DIY | PLP | Filter \u2013"+g),J(38354,"DIY | PLP | Filter \u2013"+g))}S(e,'a[data-test-id="secure-app-home-link"]')&&"/checkout"==V&&h(function(){Ya("cs-popin-cart-abandonment")},
function(){var k=document.querySelector('h2[data-test-id="alert-title"]');return k?-1<k.textContent.indexOf("want to leave checkout"):!1},250,40);g=e.innerText;S(e,"button")&&g&&("/checkout"==V&&"Find address"==g&&h(function(){Ya("cs-popin-select-address")},function(){return!!document.querySelector('[data-test-id="address-select-alert"]')},250,40),Va[g]?(Q(Va[g]),J(38355,Va[g]),"Add to basket"==g&&h(function(){Ya("cs-popin-add-to-cart")},function(){var k=document.querySelector('p[data-test-id="modal-notification-text"]');
return k?-1<k.textContent.indexOf("added to basket"):!1},250,40)):/Add .+ to basket/.test(g)&&Q(fa(g)));S(e,"[data-test-id=product-panel]")&&e.querySelector("img[src*=new_low_price]")&&(J(38355,"DIY | PLP | New low price"),Q("DIY | PLP | New low price"));var p=document.querySelector("h1.seo-title-heading");S(e,".promo-blocks article")&&((g=T(e,".promo-blocks"))&&g.querySelector(".promo-blocks h2")?(Q("DIY | Categories | "+g.querySelector(".promo-blocks h2").innerText),J(38356,"DIY | Categories | "+
g.querySelector(".promo-blocks h2").innerText)):p&&(Q("DIY | Categories | "+p.innerText),J(38356,"DIY | Categories | "+p.innerText)));S(e,'.slick-slider [data-test-id="product-panel"] button')?(Q("DIY | Categories | Upsells - Add to Basket"),J(38356,"DIY | Categories | Upsells - Add to Basket")):S(e,'.slick-slider [data-test-id="product-panel"] a[data-test-id="product-panel-main-section"]')?(Q("DIY | Categories | Upsells \u2013 Product Links"),J(38356,"DIY | Categories | Upsells \u2013 Product Links")):
S(e,'.slick-slider [data-test-id="arrow-handle-next"],.slick-slider [data-test-id="arrow-handle-previous"],.slick-slider li[class]')?(Q("DIY | Categories | Upsells \u2013 Pagination"),J(38356,"DIY | Categories | Upsells \u2013 Pagination")):S(e,".html-content img")&&-1<Ia.indexOf("departments")?(Q("DIY | Categories | Banner"),J(38356,"DIY | Categories | Banner")):S(e,".js-menu-children .menu-item")&&(g=T(e,".menus"))&&g.querySelector("a[id]")&&(g=g.querySelector("a[id]").innerText.split(",").pop().trim())&&
(Q("DIY | PLP | Filter \u2013"+g),J(38354,"DIY | PLP | Filter \u2013"+g))}.bind(e)}(c,b,this))})}}(function(a){function b(){2==++ja&&a()}ka(b);if("function"==typeof ClickTale)b();else{Array.isArray(window.ClickTaleOnReadyList)&&window.ClickTaleOnReadyList.push(b);var c=window.ClickTaleOnRecording||function(){};window.ClickTaleOnRecording=function(){b();return c.apply(this,arguments)}}})(function(){Ea();ob()});
window.clickTaleStartEventSignal=function(a){ClickTaleNote("clickTaleStartEventSignal Logical Page");Ga(document.location);a&&"string"===typeof a&&Q(a)};window.clickTaleEndEventSignal=function(){ClickTaleNote("clickTaleEndEventSignal Stop");ua()};
                })();
            } 
        }, function () { return !!(window.ClickTaleSettings && ClickTaleSettings.PTC && typeof ClickTaleSettings.PTC.okToRunPCC != 'undefined'); }, 500, 20);


//Signature:BZFGBxIe8na8v8yVjqYvE9R7lh2Qah+2ugsQ7gFJOU9Zfpy9oHLU6k8/88EHmr0RH/zcyNPgAB73WjC8Xm+OBQZiFFEWsZvy+tOSdm8B4Zv8bGWK7dA9xYJxzA4oZW/syM9q6bsAbv2ek8LhgIEtka1gWTZ1QjeuNKRIMxxCwQI=